// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCO54kUQbu75H7uobLqlnf2847rKvVHYc',
    appId: '1:100200169637:web:8c863252ca28fa99c8cd4c',
    messagingSenderId: '100200169637',
    projectId: 'find-it-fast-app',
    authDomain: 'find-it-fast-app.firebaseapp.com',
    storageBucket: 'find-it-fast-app.appspot.com',
    measurementId: 'G-HFTC0JXJH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx2JGiO2TqC8LaRn-vPMUOBVEF312neoY',
    appId: '1:100200169637:android:20f3f3f9116c24cfc8cd4c',
    messagingSenderId: '100200169637',
    projectId: 'find-it-fast-app',
    storageBucket: 'find-it-fast-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0OJdIgHmx_llRcPOkqtRAuyNwy_leyM',
    appId: '1:100200169637:ios:e50f375df254c99fc8cd4c',
    messagingSenderId: '100200169637',
    projectId: 'find-it-fast-app',
    storageBucket: 'find-it-fast-app.appspot.com',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0OJdIgHmx_llRcPOkqtRAuyNwy_leyM',
    appId: '1:100200169637:ios:e50f375df254c99fc8cd4c',
    messagingSenderId: '100200169637',
    projectId: 'find-it-fast-app',
    storageBucket: 'find-it-fast-app.appspot.com',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCO54kUQbu75H7uobLqlnf2847rKvVHYc',
    appId: '1:100200169637:web:aec7ea3c787c836fc8cd4c',
    messagingSenderId: '100200169637',
    projectId: 'find-it-fast-app',
    authDomain: 'find-it-fast-app.firebaseapp.com',
    storageBucket: 'find-it-fast-app.appspot.com',
    measurementId: 'G-Q99L4RXF4M',
  );
}
